// <auto-generated />
namespace Employee_CRUD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class abcmig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(abcmig));
        
        string IMigrationMetadata.Id
        {
            get { return "202112011705388_abc-mig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
